name: Cadence test suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install flow CLI
        run: sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"
      - name: Initialize a flow.json
        run: |
          export PATH="$PATH:$HOME/.local/bin"
          flow init
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm run test
